service: serverless-aws-step-functions

frameworkVersion: "3"
useDotenv: true

provider:
  name: aws
  runtime: python3.9
  region: us-east-1
  profile: ${env:PROFILE} # Read env variable
  memorySize: 128

functions:
  hello:
    handler: handler.hello
  world:
    handler: handler.world

stepFunctions:
  stateMachines:
    serverlessDemo:
      name: serverlessDemo
      useExactVersion: true # Blue green deployment
      definition:
        Comment: "An example of the Amazon States Language"
        StartAt: FirstState
        States:
          FirstState:
            Type: Task
            Resource:
              Fn::GetAtt: [hello, Arn]
            Next: WaitUsingSeconds
          WaitUsingSeconds:
            Type: Wait
            Seconds: 10
            Next: FinalState
          FinalState:
            Type: Task
            Resource:
              Fn::GetAtt: [world, Arn]
            End: true

plugins:
  - serverless-offline
  - serverless-step-functions
