service: serverless-aws-step-functions

frameworkVersion: "3"
useDotenv: true

provider:
  name: aws
  runtime: python3.9
  region: ap-southeast-2
  profile: ${env:PROFILE}
  memorySize: 128

functions:
  hello:
    handler: handler.hello

stepFunctions:
  stateMachines:
    serverlessDemo:
      name: serverlessDemo
      useExactVersion: true # Blue green deployment
      definition:
        Comment: "An example of the Amazon States Language using wait states"
        StartAt: FirstState
        States:
          FirstState:
            Type: Task
            Resource:
              Fn::GetAtt: [hello, Arn]
            Next: WaitUsingSeconds
          WaitUsingSeconds:
            Type: Wait
            Seconds: 10
            Next: FinalState
          FinalState:
            Type: Task
            Resource:
              Fn::GetAtt: [hello, Arn]
            End: true

plugins:
  - serverless-offline
  - serverless-step-functions
