service: serverless-aws-step-functions

frameworkVersion: "3"
useDotenv: true

provider:
  name: aws
  runtime: python3.9
  region: us-east-1
  profile: ${env:PROFILE} # Read env variable
  memorySize: 128

functions:
  hello:
    handler: handler.hello
  world:
    handler: handler.world

stepFunctions:
  stateMachines:
    serverlessDemo:
      name: serverlessDemo
      useExactVersion: true # Blue green deployment
      definition:
        Comment: "An example of the Amazon States Language"
        StartAt: FirstState
        States:
          FirstState:
            Type: Task
            Resource:
              Fn::GetAtt: [hello, Arn]
            Next: WaitUsingSeconds
          WaitUsingSeconds:
            Type: Wait
            Seconds: 5
            Next: FinalState
          FinalState:
            Type: Task
            Resource:
              Fn::GetAtt: [world, Arn]
            End: true
    nestDemo:
      name: nestDemo
      events:
        - http:
          path: action/start
          method: POST
      definition:
        StartAt: FirstState
        States:
          FirstState:
            Type: Task
            Resource: arn:aws:states:::states:StartSyncExecution
            Parameters:
              StateMachineArn: ${env:STATE_MACHINE_ARN}
              Input:
                NeedCallback: False
                AWS_STEP_FUNCTIONS_STARTED_BY_EXECUTION_ID.$: $$.Execution.Id
            Next: SecondState
          SecondState:
            Type: Task
            Resource: arn:aws:states:::states:StartSyncExecution
            Parameters:
              StateMachineArn: ${env:STATE_MACHINE_ARN}
              Input:
                NeedCallback: False
                AWS_STEP_FUNCTIONS_STARTED_BY_EXECUTION_ID.$: $$.Execution.Id
            Next: FinalState
          FinalState:
            Type: Task
            Resource: arn:aws:states:::states:StartSyncExecution
            Parameters:
              StateMachineArn: ${env:STATE_MACHINE_ARN}
              Input:
                NeedCallback: False
                AWS_STEP_FUNCTIONS_STARTED_BY_EXECUTION_ID.$: $$.Execution.Id
            End: true

plugins:
  - serverless-offline
  - serverless-step-functions
